package TPE;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class SendEmail {

    public static void send(String to, String p, String d, String t) {

        String user = "turnofacilxd@gmail.com";
        String pass = "opndrdrigaapyqhq";
        String host = "smtp.gmail.com";
        Properties props = System.getProperties();

        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.auth", "true");
  
        Session session = Session.getInstance(props, new javax.mail.Authenticator() {

            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(user, pass);
            }

        });
        //session.setDebug(true);

        try {

            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(user));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.setContent("<div class=\"\"><div class=\"aHl\"></div><div id=\":14p\" tabindex=\"-1\"></div><div id=\":14e\" class=\"ii gt\" jslog=\"20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0.\"><div id=\":14d\" class=\"a3s aiL msg6460170773642741920\"><u></u>\r\n"
            		+ "\r\n"
            		+ "\r\n"
            		+ "\r\n"
            		+ "  \r\n"
            		+ "  \r\n"
            		+ "  \r\n"
            		+ "  \r\n"
            		+ "\r\n"
            		+ "  \r\n"
            		+ "\r\n"
            		+ "\r\n"
            		+ "<div>\r\n"
            		+ "  <table role=\"presentation\" style=\"opacity:1\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "    <tbody>\r\n"        
            		+ "                <td class=\"m_6460170773642741920o_sans\" style=\"font-family:Helvetica,Arial,sans-serif;margin-top:0px;margin-bottom:0px;font-size:16px;line-height:24px;background-color:rgb(245,245,245);border-radius:4px 4px 0px 0px;padding:24px 16px\" align=\"center\">\r\n"
            		+ "                  <p style=\"margin-top:0px;margin-bottom:0px\">\r\n"
            		+ "                    \r\n"
            		+ "                      <a href=\"https://mandrillapp.com/track/click/30996605/drapp.com.ar?p=eyJzIjoidjdXUHF3UHh5RjZ0TEJaZEx6aEIyVjNqNHQ4IiwidiI6MSwicCI6IntcInVcIjozMDk5NjYwNSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2RyYXBwLmNvbS5hclxcXC9cIixcImlkXCI6XCIyYzU4ZTIyYTA3YWM0NTBiYWNhOTU5MGY2NWIzMDY0YVwiLFwidXJsX2lkc1wiOltcIjJhYzg1ZTk1YWJmYzVkOGU4NWVmMjhkNGQxMGY0YzE0N2VjZmFiMWNcIl19In0\" style=\"text-decoration:none;color:#ffffff;outline:none\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://mandrillapp.com/track/click/30996605/drapp.com.ar?p%3DeyJzIjoidjdXUHF3UHh5RjZ0TEJaZEx6aEIyVjNqNHQ4IiwidiI6MSwicCI6IntcInVcIjozMDk5NjYwNSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2RyYXBwLmNvbS5hclxcXC9cIixcImlkXCI6XCIyYzU4ZTIyYTA3YWM0NTBiYWNhOTU5MGY2NWIzMDY0YVwiLFwidXJsX2lkc1wiOltcIjJhYzg1ZTk1YWJmYzVkOGU4NWVmMjhkNGQxMGY0YzE0N2VjZmFiMWNcIl19In0&amp;source=gmail&amp;ust=1655259083389000&amp;usg=AOvVaw3UAOZV-Pe5ixfLWhzRh4p7\">\r\n"
            		+ "                        <img src=\"https://raw.githubusercontent.com/FelipePipe2002/TrabajoMetodologia/master/ProjectJava/src/logo.png\" alt=\"turnoFacil\" style=\"max-width:136px;vertical-align:middle;border:0;line-height:100%;height:auto;outline:none;text-decoration:none\" width=\"136\" height=\"36\" class=\"CToWUd\">\r\n"
            		+ "                      </a>\r\n"
            		+ "                    \r\n"
            		+ "                  </p>\r\n"
            		+ "                </td>\r\n"
            		+ "              </tr>\r\n"
            		+ "            </tbody>\r\n"
            		+ "          </table>\r\n"
            		+ "          \r\n"
            		+ "        </td>\r\n"
            		+ "      </tr>\r\n"
            		+ "    </tbody>\r\n"
            		+ "  </table>\r\n"      
            		+ "          <table style=\"max-width:632px;margin:0 auto\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "            <tbody>\r\n"
            		+ "              <tr>\r\n"
            		+ "                <td class=\"m_6460170773642741920o_xs-py-md m_6460170773642741920o_sans\" style=\"font-family:Helvetica,Arial,sans-serif;margin-top:0px;margin-bottom:0px;font-size:19px;line-height:28px;background-color:#ffffff;color:#82899a;padding-left:24px;padding-right:24px;padding-top:64px;padding-bottom:25px\" align=\"center\">\r\n"
            		+ "                  <table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "                    <tbody>\r\n"
            		+ "                      <tr>\r\n"
            		+ "                        <td class=\"m_6460170773642741920o_sans\" style=\"font-family:Helvetica,Arial,sans-serif;margin-top:0px;margin-bottom:0px;font-size:16px;line-height:24px;background-color:rgb(118,184,35);color:rgb(255,255,255);border-radius:96px;padding:16px\" align=\"center\">\r\n"
            		+ "                          <img src=\"https://ci4.googleusercontent.com/proxy/ow4KxLkTKvUHI9f9oBJmj3jAsy5p_xZOaah6fsMFkv6Q-C3uABH9rewNDRc4HKklD_5sO2J8SPAKbrhTlJMNszUJNDiicHL_EalRfgDd0DA_nbTDw0ZtKc4v3JIr0EvNZWA5pev_mUQuz4wtacccRD-TGlJ7cvs941s=s0-d-e1-ft#https://gallery.mailchimp.com/336d436794aab535ddeb48c60/images/aa9fa96d-2611-40a7-8762-912830f54ec5.png\" alt=\"\" style=\"max-width:48px;vertical-align:middle;border:0;line-height:100%;height:auto;outline:none;text-decoration:none\" width=\"48\" height=\"48\" class=\"CToWUd\">\r\n"
            		+ "                        </td>\r\n"
            		+ "                      </tr>\r\n"
            		+ "                      <tr>\r\n"
            		+ "                        <td style=\"font-size:24px;line-height:24px;height:24px\">\r\n"
            		+ "                        </td>\r\n"
            		+ "                      </tr>\r\n"
            		+ "                    </tbody>\r\n"
            		+ "                  </table>\r\n"
            		+ "                  <h2 class=\"m_6460170773642741920o_heading\" style=\"font-family:Helvetica,Arial,sans-serif;font-weight:bold;margin-top:0px;margin-bottom:4px;color:#242b3d;font-size:30px;line-height:39px\">\r\n"
            		+ "      ¡Recordatorio!<br>\r\n"
            		+ "      </h2>\r\n"
            		+ "                  <p style=\"margin-top:0px;margin-bottom:0px\">\r\n"
            		+ "                    Recorda el <span class=\"il\">turno</span> de <span style=\"color:#000\">" + p + "</span> con <span style=\"color:#000\">" + d + "</span>\r\n"
            		+ "                    <br>\r\n"
            		+ "                  </p>\r\n"
            		+ "                </td>\r\n"
            		+ "              </tr>\r\n"
            		+ "            </tbody>\r\n"
            		+ "          </table>\r\n"
            		+ "          \r\n"
            		+ "        </td>\r\n"
            		+ "      </tr>\r\n"
            		+ "    </tbody>\r\n"
            		+ "  </table>\r\n"
            		+ "  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "    <tbody>\r\n"
            		+ "      <tr>\r\n"
            		+ "        <td style=\"background-color:rgb(245,245,245);padding-left:8px;padding-right:8px\" align=\"center\">\r\n"
            		+ "          \r\n"
            		+ "          <table role=\"presentation\" style=\"max-width:632px;margin:0 auto\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "            <tbody>\r\n"
            		+ "              <tr>\r\n"
            		+ "                <td class=\"m_6460170773642741920o_sans\" style=\"font-family:Helvetica,Arial,sans-serif;margin-top:0px;margin-bottom:0px;font-size:14px;line-height:21px;background-color:#ffffff;color:#82899a;padding-left:24px;padding-right:24px;padding-top:16px;padding-bottom:16px\" align=\"center\">\r\n"
            		+ "                  <p style=\"margin-top:0px;margin-bottom:16px\">\r\n"
            		+ "                    <strong>\r\n"
            		+ "      Estos son los datos del <span class=\"il\">turno</span>:</strong>\r\n"
            		+ "                    <br><strong>\r\n"
            		+ "      </strong>\r\n"
            		+ "                  </p>\r\n"
            		+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "                    <tbody>\r\n"
            		+ "                      <tr>\r\n"
            		+ "                        <td class=\"m_6460170773642741920o_sans\" style=\"font-family:Helvetica,Arial,sans-serif;margin-top:0px;margin-bottom:0px;font-size:24px;line-height:30px;background-color:#ebf5fa;border-radius:4px;padding-left:8px;padding-right:8px;padding-top:24px;padding-bottom:24px\" width=\"284\" align=\"center\">\r\n"
            		+ "                          <p style=\"color:#242b3d;margin-top:0px;margin-bottom:0px\">\r\n"
            		+ "                            <strong>" + t + "<br></strong>\r\n"
            		+ "                          </p>\r\n"
            		+ "                        </td>\r\n"
            		+ "                      </tr>\r\n"
            		+ "                    </tbody>\r\n"
            		+ "                  </table>\r\n"
            		+ "                </td>\r\n"
            		+ "              </tr>\r\n"
            		+ "            </tbody>\r\n"
            		+ "          </table>\r\n"
            		+ "          \r\n"
            		+ "        </td>\r\n"
            		+ "      </tr>\r\n"
            		+ "    </tbody>\r\n"
            		+ "  </table>\r\n"
            		+ "  <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "    <tbody>\r\n"
            		+ "      <tr>\r\n"
            		+ "        <td style=\"background-color:rgb(245,245,245);padding-left:8px;padding-right:8px\" align=\"center\">\r\n"
            		+ "          \r\n"
            		+ "          <table style=\"max-width:632px;margin:0 auto\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "            <tbody>\r\n"
            		+ "              <tr>\r\n"
            		+ "                <td style=\"background-color:#ffffff;padding-left:24px;padding-right:24px\" align=\"center\">\r\n"
            		+ "                  <table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "                    <tbody>\r\n"
            		+ "                      \r\n"
            		+ "                      <tr>\r\n"
            		+ "                        <td class=\"m_6460170773642741920o_sans\" style=\"font-family:Helvetica,Arial,sans-serif;margin-top:0px;margin-bottom:0px;font-size:16px;line-height:24px;color:rgb(130,137,154);border-bottom:1px solid rgb(211,220,224);padding-top:16px;padding-bottom:16px;text-align:center\" width=\"450\" align=\"left\">\r\n"
            		+ "                        \r\n"
            		+ "                      <p style=\"margin-top:0px;margin-bottom:0px\">\r\n"
            		+ "                            <span style=\"display:inline\">" + "Direccion" + "</span>\r\n"
            		+ "                          </p>\r\n"
            		+ "                          \r\n"
            		+ "                        </td>\r\n"
            		+ "                      </tr>\r\n"
            		+ "                      \r\n"
            		+ "                        \r\n"
            		+ "                    </tbody>\r\n"
            		+ "                  </table>\r\n"
            		+ "                </td>\r\n"
            		+ "              </tr>\r\n"
            		+ "            </tbody>\r\n"
            		+ "          </table>\r\n"
            		+ "          \r\n"
            		+ "        </td>\r\n"
            		+ "      </tr>\r\n"
            		+ "    </tbody>\r\n"
            		+ "  </table>\r\n"
            		+ "  <table role=\"presentation\" style=\"opacity:1\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "    <tbody>\r\n"
            		+ "      <tr>\r\n"
            		+ "        <td style=\"background-color:rgb(245,245,245);padding-left:8px;padding-right:8px\" align=\"center\">\r\n"
            		+ "          \r\n"
            		+ "          <table role=\"presentation\" style=\"max-width:632px;margin:0 auto\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"          
            		+ "          </table>\r\n"
            		+ "            \r\n"
            		+ "                               \r\n"
            		+ "          \r\n"
            		+ "        </td>\r\n"
            		+ "      </tr>\r\n"
            		+ "    </tbody>\r\n"
            		+ "  </table>\r\n"
            		+ "  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "    <tbody>\r\n"
            		+ "      <tr>\r\n"
            		+ "        <td style=\"background-color:rgb(245,245,245);padding-left:8px;padding-right:8px\" align=\"center\">\r\n"
            		+ "          \r\n"
            		+ "          <table role=\"presentation\" style=\"max-width:632px;margin:0 auto\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "            <tbody>\r\n"
            		+ "              <tr>\r\n"
            		+ "                <td style=\"font-size:48px;line-height:48px;height:48px;background-color:#ffffff\">\r\n"
            		+ "                </td>\r\n"
            		+ "              </tr>\r\n"
            		+ "            </tbody>\r\n"
            		+ "          </table>\r\n"
            		+ "          \r\n"
            		+ "        </td>\r\n"
            		+ "      </tr>\r\n"
            		+ "    </tbody>\r\n"
            		+ "  </table>\r\n"
            		+ "  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "    <tbody>\r\n"
            		+ "      <tr>\r\n"
            		+ "        <td style=\"background-color:rgb(245,245,245);padding-left:8px;padding-right:8px\" align=\"center\">\r\n"
            		+ "          \r\n"
            		+ "          <table role=\"presentation\" style=\"max-width:632px;margin:0 auto\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "            <tbody>\r\n"
            		+ "              <tr>\r\n"
            		+ "                <td style=\"font-size:0px;vertical-align:top;background-color:rgb(222,222,222);padding-left:16px;padding-right:16px;padding-bottom:24px\" align=\"center\">\r\n"
            		+ "                  \r\n"
            		+ "                  <div style=\"display:inline-block;vertical-align:top;width:100%;max-width:300px\">\r\n"
            		+ "                    <div style=\"font-size:24px;line-height:24px;height:24px\">\r\n"
            		+ "                    </div>\r\n"
            		+ "                    <div class=\"m_6460170773642741920o_sans m_6460170773642741920o_xs-center\" style=\"font-family:Helvetica,Arial,sans-serif;margin-top:0px;margin-bottom:0px;font-size:16px;line-height:24px;color:#424651;text-align:left;padding-left:8px;padding-right:8px\">\r\n"
            		+ "                      <p style=\"margin-top:0px;margin-bottom:4px\">\r\n"
            		+ "                        <strong>\r\n"
            		+ "          ¿Necesitas cancelar el <span class=\"il\">turno</span>?<br></strong>\r\n"
            		+ "                        <span style=\"font-size:12px;line-height:19px\">\r\n"
            		+ "          </span>\r\n"
            		+ "                      </p>\r\n"
            		+ "                      <p style=\"font-size:14px;line-height:21px;margin-top:0px;margin-bottom:0px\">\r\n"
            		+ "                        ¡Hacelo en 2 Clicks!\r\n"
            		+ "                        <br>\r\n"
            		+ "                      </p>\r\n"
            		+ "                    </div>\r\n"
            		+ "                  </div>\r\n"
            		+ "                  \r\n"
            		+ "                  <div style=\"display:inline-block;vertical-align:top;width:100%;max-width:300px\">\r\n"
            		+ "                    <div style=\"font-size:24px;line-height:24px;height:24px\">\r\n"
            		+ "                    </div>\r\n"
            		+ "                    <div class=\"m_6460170773642741920o_xs-center\" style=\"text-align:right;padding-left:8px;padding-right:8px\">\r\n"
            		+ "                      <table class=\"m_6460170773642741920o_xs-center\" role=\"presentation\" style=\"text-align:right;margin-left:auto;margin-right:0\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "                        <tbody>\r\n"
            		+ "                          <tr>\r\n"
            		+ "                            <td class=\"m_6460170773642741920o_heading\" style=\"font-family:Helvetica,Arial,sans-serif;font-weight:bold;margin-top:0px;margin-bottom:0px;font-size:16px;line-height:24px;background-color:rgb(207,94,100);border-radius:4px\" align=\"center\">\r\n"
            		+ "                              <a href=\"https://www.drapp.com.ar/cancelar/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhYmFzZSI6InVzZXJkYi02Y2NjYmQxMzg5YjUwMzg1YjM2NGVmMGI0YzU4NjU4MiIsImFwcHRJRCI6ImFwcHQtNjk0ZmRlMDExMDJiZTc5ZSIsInRva2VuIjoiNjJhNWFkMmU4Yjc4MjFkNjQ3MGRjZmI1YTc5NjkxOWExNTg0YzgyYyIsImlhdCI6MTY0MDUyOTY2NH0.dkBaNv1ib50DxzIxV2uUf4zbfMvQ-OflgjFXS4rRpLrFkb8x_wUblch6e0-rkj6yn3UVqQonD-uXTlt4W3LycPNj-F-JTdxSqoxO_4roy0_L-UrRgTjNmCf_hkuuMwcvxnSxgNrlUXScGFpwjKdAtOB4MHrsxusi2kwK8BMTDJ9FdvroqR-ctvq7KoZuwfRFFZGuJzYxnuKW-EvILRvtY6Ub1DGJY9Ii5vzABFIS1GLArHz8g9DfeBWHzkj8KefrAvrkfchXDeh4E-6iRh32yF8mQkhGnO6QprVwCTW3qo9xg5SnXerQtv19KbJTCskd3_Z-Hi4SfGmdPxDFkZZBxJ5spkENXV5Kxlwohto1FneRWZaJW4VflXekivA0KRLoBGJ6mjWbSIpx47LwMKeXKnh1kURFU67ahZbFjy_dGTzShK7euYehzZt7FOluyTktiPTyy2i-K2ZcSXca9JLA6q10sThI4gq1-sCZVoRh7OC_N022pCNa4OuflUGwVDgQVTKCnmHYmj7WTLWZEy5hXEQ9pHFit-Y19BscLXOH-dvldOCflFiGpx-w74UdOJt3Bvf9X5-58LPvD3biClb44GH_h-qvB3F9enuxItxopZFPFPAcWHNGlVHnaodAeNm722k5f_UO6CKwJsiNtZps4m6rpInuFxj7pl9OH94f7Rk\" style=\"text-decoration:none;color:#ffffff;display:block;padding:12px 24px;outline:none\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://www.drapp.com.ar/cancelar/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhYmFzZSI6InVzZXJkYi02Y2NjYmQxMzg5YjUwMzg1YjM2NGVmMGI0YzU4NjU4MiIsImFwcHRJRCI6ImFwcHQtNjk0ZmRlMDExMDJiZTc5ZSIsInRva2VuIjoiNjJhNWFkMmU4Yjc4MjFkNjQ3MGRjZmI1YTc5NjkxOWExNTg0YzgyYyIsImlhdCI6MTY0MDUyOTY2NH0.dkBaNv1ib50DxzIxV2uUf4zbfMvQ-OflgjFXS4rRpLrFkb8x_wUblch6e0-rkj6yn3UVqQonD-uXTlt4W3LycPNj-F-JTdxSqoxO_4roy0_L-UrRgTjNmCf_hkuuMwcvxnSxgNrlUXScGFpwjKdAtOB4MHrsxusi2kwK8BMTDJ9FdvroqR-ctvq7KoZuwfRFFZGuJzYxnuKW-EvILRvtY6Ub1DGJY9Ii5vzABFIS1GLArHz8g9DfeBWHzkj8KefrAvrkfchXDeh4E-6iRh32yF8mQkhGnO6QprVwCTW3qo9xg5SnXerQtv19KbJTCskd3_Z-Hi4SfGmdPxDFkZZBxJ5spkENXV5Kxlwohto1FneRWZaJW4VflXekivA0KRLoBGJ6mjWbSIpx47LwMKeXKnh1kURFU67ahZbFjy_dGTzShK7euYehzZt7FOluyTktiPTyy2i-K2ZcSXca9JLA6q10sThI4gq1-sCZVoRh7OC_N022pCNa4OuflUGwVDgQVTKCnmHYmj7WTLWZEy5hXEQ9pHFit-Y19BscLXOH-dvldOCflFiGpx-w74UdOJt3Bvf9X5-58LPvD3biClb44GH_h-qvB3F9enuxItxopZFPFPAcWHNGlVHnaodAeNm722k5f_UO6CKwJsiNtZps4m6rpInuFxj7pl9OH94f7Rk&amp;source=gmail&amp;ust=1655259083389000&amp;usg=AOvVaw2UiRTlNpwrOV45Zddw8GvK\">\r\n"
            		+ "            Cancelar <span class=\"il\">Turno</span></a>\r\n"
            		+ "                            </td>\r\n"
            		+ "                          </tr>\r\n"
            		+ "                        </tbody>\r\n"
            		+ "                      </table>\r\n"
            		+ "                    </div>\r\n"
            		+ "                    \r\n"
            		+ "                  </div>\r\n"
            		+ "                </td>\r\n"
            		+ "              </tr>\r\n"
            		+ "            </tbody>\r\n"
            		+ "          </table>\r\n"
            		+ "          \r\n"
            		+ "        </td>\r\n"
            		+ "      </tr>\r\n"
            		+ "    </tbody>\r\n"
            		+ "  </table>\r\n"
            		+ "\r\n"
            		+ "  <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "    <tbody>\r\n"
            		+ "      <tr>\r\n"
            		+ "        <td class=\"m_6460170773642741920o_xs-pb-xs\" style=\"background-color:rgb(245,245,245);padding-left:8px;padding-right:8px;padding-bottom:32px\" align=\"center\">\r\n"
            		+ "          \r\n"
            		+ "          <table style=\"max-width:632px;margin:0 auto\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
            		+ "            <tbody>\r\n"
            		+ "              <tr>\r\n"
            		+ "\r\n"
            		+ "              </tr>\r\n"
            		+ "              <tr>\r\n"
            		+ "                \r\n"
            		+ "                  <td class=\"m_6460170773642741920o_sans\" style=\"padding-top:32px;font-family:Helvetica,Arial,sans-serif;margin-top:0px;margin-bottom:0px;font-size:14px;line-height:21px;background-color:#13629b;color:#fff;border-radius:0px 0px 4px 4px;padding-left:24px;padding-right:24px;padding-bottom:32px\" align=\"center\">\r\n"
            		+ "                    <p style=\"margin-top:0px;margin-bottom:8px\">\r\n"
            		+ "                      ©2022 turnoFacil\r\n"
            		+ "                      <br> UNICEN - Educativo "
            		+ "                      <br> Buenos Aires, Argentina </p>\r\n"
            		+ "                  </td>\r\n"
            		+ "                \r\n"
            		+ "              </tr>\r\n"
            		+ "            </tbody>\r\n"
            		+ "          </table>\r\n"
            		+ "          \r\n"
            		+ "          <div class=\"m_6460170773642741920o_hide-xs\" style=\"font-size:64px;line-height:64px;height:64px\">\r\n"
            		+ "          </div>\r\n"
            		+ "        </td>\r\n"
            		+ "      </tr>\r\n"
            		+ "    </tbody>\r\n"
            		+ "  </table>\r\n"
            		+ "<img src=\"https://ci6.googleusercontent.com/proxy/sZeSTOtEqtC8wv5NkACvUGf0mYVoBQNiXvYvyPEktVrUwEm72967n5ew-j9uZG0EDejN1e1P7BK6gKZutSx9aEBCpQmis64GhPWs7VPAlFMYLzGNlMseRu5Yy5ySBg_9111Fqe4pTMw=s0-d-e1-ft#https://mandrillapp.com/track/open.php?u=30996605&amp;id=2c58e22a07ac450baca9590f65b3064a\" height=\"1\" width=\"1\" class=\"CToWUd\"></div><div class=\"yj6qo\"></div><div class=\"adL\">\r\n"
            		+ "\r\n"
            		+ "</div></div></div><div id=\":14t\" class=\"ii gt\" style=\"display:none\"><div id=\":14u\" class=\"a3s aiL \"></div></div><div class=\"hi\"></div></div>", "text/html");
            
            System.out.println("Sending message...");

            Transport.send(message);
            
            System.out.println("Sent message successfully....");
            
        } catch (MessagingException mex) {
            mex.printStackTrace();
        }

    }

}